ckpt_dir: D:\graduate\mine_attention\checkpoints
vocab_dict: D:\graduate\mine_attention\dictionary\vocab.dict
w2v_model: D:\graduate\mine_attention\word2vec\w2v_model
lda_model: D:\graduate\mine_attention\LDA\model
lda_vocab: D:\graduate\mine_attention\LDA\dict
num_classes: 263
max_gradient_norm: 5.0
batch_size: 1
num_hidden_units: 256
embedding_size: 150
num_layers: 2
dropout: 0.6
en_vocab_size: 200000
pos_weight: 1000