# Generated by Django 2.1.4 on 2019-02-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wenshu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wenshu_id', models.CharField(max_length=20)),
                ('accu', models.CharField(max_length=100)),
                ('law', models.TextField()),
                ('topic_vector', models.TextField()),
            ],
            options={
                'db_table': 'wenshu_table',
            },
        ),
    ]
