# Generated by Django 2.1.4 on 2019-03-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WenShuModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wenshu_Id_Filename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wenshu_id', models.CharField(max_length=20)),
                ('wenshu_filename', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'id_filename',
            },
        ),
    ]
